### ISSUE TITLE
How to work with OutputDistances object?

### ISSUE THREAD

**Issue by hsm207** [ashvardanian/SimSIMD#95]
In simsimd 3.7.7, this code:

```python
import simsimd
import numpy as np

X = np.array([[1, 2, 3]], dtype=np.float32)
Y = np.array([[4, 5, 6]], dtype=np.float32)

simsimd.cosine(X, Y)
```
returns

```bash
array([0.02940369], dtype=float32)
```

but in 3.9.0, it now returns:

```
<simsimd.OutputDistances at 0xffff6257ec70>
```

how do I get the result like in 3.7.7?

**Comment by ashvardanian** [comment]
Hi, @hsm207! Have you tried wrapping via `np.array`?

**Comment by ashvardanian** [comment]
I had to change this behavior to output a generic buffer instead of NumPy array, because the latter supports fewer platforms than SimSIMD, so we can’t always rely on NumPy types. The provided output, however, must be safely convertible to any tensor type in NumPy, PyTorch, TensorFlow, or any other numeric library.

I’m sorry for the inconvenience it may have caused, I didn’t realize many depended on the exact type. I can probably added to the README. Feel free to a documentation patch if you have a minute 🤗

**Comment by maiqingqiang** [comment]
> Hi, @hsm207! Have you tried wrapping via `np.array`?

How to wrap it with np.array? Is there a reference example?

**Comment by ashvardanian** [comment]
Have you tried simply passing the output into the np.array function?

**Comment by ashvardanian** [comment]
Commit c09d895de05d2cc4d8854cb4a99e99cb054563c9 explicitly describes conversion rules. Hope this helps 🤗
